### PR TITLE
[NDS-846] Viewport storybook addon 

### PR DESCRIPTION
**Pull request by matthewlyle**
This PR adds an addon to storybook that allows us to easily view components at different browser sizes.

### CODE REVIEW

**Comment by matthewlyle** [comment]
Hm, passing `yarn test` locally but failing travis due to `The command "eval yarn " failed.`

**Comment by matthewlyle** [comment]
Ah because for some reason my yarn add created a package.json. That's probably the issue.

**Comment by matthewlyle** [comment]
Ah because my upgrade of storybook upgraded React. Will look into reducing version back.

**Comment by nikola-nulogy** [comment]
Shouldn't extra small be 320px?

**Comment by matthewlyle** [comment]
> Shouldn't extra small be 320px?

yes.

**Review by nikola-nulogy — APPROVED** [review]

**Comment by matthewlyle** [comment]
Apparently the issue is a wrong version of storybook-react. Trying to fix now.

**Pull request merged**
